# Site settings
title: Rafael Souza
email: contato@rafaelfcsouza.com.br
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: 
github_username: rafaelfcsouza
linkedin_username: rafaelfcsouza

# Build settings
markdown: kramdown
remote_theme: poole/poole
plugins:
  - jekyll-feed
