languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://rafaelfcsouza.com/"
title = "Rafael Souza - CV"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#fff"
colorPrimary = "#000"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#000"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#000"
pages = 2
# Set this param to 'true' to swap the bar positions
swapColumns = false
