baseURL = 'https://rafaelfcsouza.com/'
locale = 'en-us'
title = 'Rafael Souza'

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[module]
[[module.imports]]
path = 'github.com/google/docsy'
